# Default to Windows for local development
# [build]
# target = "x86_64-unknown-linux-gnu"

# Uncomment for Linux cross-compilation (requires Docker + cross)
# [target.x86_64-unknown-linux-gnu]
# linker = "x86_64-linux-gnu-gcc"
