name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build for Linux
      run: cargo build --release
    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: server-linux
        path: target/release/server